### ISSUE TITLE
Example configuration for external clickhouse?

### ISSUE THREAD

**Issue by arrowcircle** [flant/loghouse#146]
Hi! Thanks for the great work.
I am trying to install loghouse with external clickhouse server, but have a problem. I always get config errors.

If I set server name to dns name inside kubernetes cluster, I get error about `.` in name:

```yaml
clickhouse:
  external: true
  server: clickhouse.clickhouse
...
```

If I add external endpoints, it requires IP address:

```yaml
clickhouse:
  external: true
  externalEndpoints:
    - clickhouse.clickhouse
...
```

What is the proper way (or example) setting loghouse with external clickhouse?

**Comment by gyrter** [comment]
Hello. You can use this code in chart values. Only IP allowed.

If you want to use loghouse with k8s clickhouse - use Cluster IP for you service.

```
clickhouse:
  external: false
  externalEndpoints:
  - 172.17.0.2
```
