### ISSUE TITLE
Helm chart is not compatible with the current cert-manager stable release

### ISSUE THREAD

**Issue by davojan** [flant/loghouse#150]
When trying to install loghouse along with current [cert-manager release 0.14.2](https://github.com/jetstack/cert-manager/releases/tag/v0.14.2) this error happens:

```
helm.go:75: [debug] unable to recognize "": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1"
```

I believe this is because they [renamed api-group](https://github.com/jetstack/cert-manager/blob/930827b06bc03afd021fde49907095eac4784d0d/design/release-notes/release-0.11/draft-release-notes.md#L7) to ``cert-manager.io``

**Comment by serggend** [comment]
for my example i just add 
``` 
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
```
in this part of values
```
loghouse:
    host: loghouse.domain.com
    path: "/"
    tls_secret_name: loghouse
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
```
and it works ( but i already have clusterissuer, all env for letsencrypt and etc... )
