### ISSUE TITLE
Fluend - Connection refused on docker container

### ISSUE THREAD

**Issue by RouR** [flant/loghouse#79]
Please add to docker image flant/loghouse-fluentd: 

```
 ports:
    - 24224:24224
```

Please add to ConfigMap fluentd-config:

```
<source>
      @type forward
      port 24224
      bind 0.0.0.0
</source>   
```  

Please add to DaemonSet fluentd:

```
ports:
        - name: http-input
          containerPort: 24224
          protocol: TCP    
``` 

I hope it will fix error "Fluentd Connection refused 127.0.0.1:24224" from another docker image on the same node
